### ISSUE TITLE
Include correct frame and ROI to CameraInfo message

### ISSUE THREAD

**Issue by MaslinuPoimal** [tum-phoenix/drive_ros_ximea_importer#2]
This needed for correct world/image transformations.

**Comment by MaslinuPoimal** [comment]
Frame has been moved to config, ROI should be extracted from Ximea-internal cropping happening in the driver when using the camerainfo setting service.

**Comment by fabolhak** [comment]
Hey, I already did this: https://github.com/tum-phoenix/drive_ros_ximea_importer/commit/e51f71912d853bb0a9609e2340b23dcc5f5d3d8b

**Comment by fabolhak** [comment]
somehow this isn't included in the homography bags. Should be investigated.

**Comment by MaslinuPoimal** [comment]
Ok, I've added the tf frame: https://github.com/tum-phoenix/drive_ros_ximea_importer/commit/bf231c5aa11cbab098ceffe413b0d3940382e4ab, will just manually modify the CameraInfo in the callback for now.

**Comment by fabolhak** [comment]
should be fixed in: https://github.com/tum-phoenix/drive_ros_ximea_importer/commit/6abb3e1926100915398b0f8ac01b4f93e3833cf8
(I screwed up the config files 🙈)
